### PR TITLE
fix: suppress access errors while fast-globbing

### LINKED ISSUE #448: Error: EACCES: permission denied, scandir '/home/xxxx/Documents/xxxx/data/mongo/.m...
Our logs are clogged by:

Sentry Issue: [VSCODE-EXTENSION-W43](https://nomic-labs.sentry.io/issues/4051558030/?referrer=github_integration)

```
Error: EACCES: permission denied, scandir '/home/xxxx/Documents/xxx/data/mongo/.mongodb'
```

We should find our where we can get these sorts of file access errors, and determine their impact and then either solve them or suppress them.

### PR DESCRIPTION
**Pull request by antico5**
The error happened when there was a file or folder without access permissions while globbing for e.g. config files. It prevented any projects from being indexed at all.

Closes #448

### CODE REVIEW

File: server/src/utils/WorkspaceFileRetriever.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@ export class WorkspaceFileRetriever {
       cwd: baseUri,
       ignore,
       followSymbolicLinks: false,
+      suppressErrors: true,
```
Comment (kanej) [inline server/src/utils/WorkspaceFileRetriever.ts:16]: Beautiful.

**Review by kanej — APPROVED** [review]
